Models/EmprestimosModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmprestimoLivros.Models
{
    public class EmprestimosModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do recebedor!")]
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "Digite o nome do fornecedor!")]
        public string Fornecedor { get; set; }

        [Required(ErrorMessage = "Digite o nome do livro!")]
        public string LivroEmprestado { get; set; }
        public DateTime dataUltimaAtualizacao { get;set; } = DateTime.Now;
    }
}

Models/ErrorViewModel.cs
namespace EmprestimoLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmprestimoController.cs
using EmprestimoLivros.Data;
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmprestimoLivros.Controllers
{
    public class EmprestimoController : Controller
    {
        readonly private ApplicationDbContext _db;
        public EmprestimoController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<EmprestimosModel> emprestimos = _db.Emprestimos; //_db.Emprestimos se refere à tabela
            return View(emprestimos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id) 
        {
            if (id == null || id ==0) 
            { 
                return NotFound();
            }

            EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id == id);   

            if(emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }


        [HttpPost]
        public IActionResult Cadastrar(EmprestimosModel emprestimos)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Add(emprestimos);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";


                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpPost]
        public IActionResult Editar(EmprestimosModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimos.Update(emprestimo);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro editado com sucesso!";

                return RedirectToAction("Index");
            }

            TempData["MensagemErro"] = "Algo de errado ocorreu!";

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimosModel emprestimo = _db.Emprestimos.FirstOrDefault(x => x.Id==id);

            if(emprestimo == null) 
            { 
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Excluir(EmprestimosModel emprestimo)
        {
            if (emprestimo == null)
            {
                return NotFound();
            }

            _db.Emprestimos.Remove(emprestimo);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Cadastro excluído com sucesso!";

            return RedirectToAction("Index");
        }

    }
}

Controllers/HomeController.cs
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Emprestimo/Cadastrar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Cadastrar Empréstimo";
}

<div class="container bg-dark p-5 rounded-3">

    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de empréstimos</h1>
    </div>

    <form method="post" asp-asp-controller="Emprestimo" asp-action="Cadastrar">

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro:</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual livro está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controler="Emprestimo" asp-action="">Voltar</a>
        </div>

   
    </form>
</div>

Views/Emprestimo/Editar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Editar Empréstimo";
}

<div class="container bg-dark p-5 rounded-3">

    <div class="mb-5 text-center">
        <h1 class="text-light">Editar empréstimos</h1>
    </div>

    <form method="post" asp-asp-controller="Emprestimo" asp-action="Editar">

        <input type="hidden" asp-for=Id />

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro:</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual livro está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controler="Emprestimo" asp-action="">Voltar</a>
        </div>


    </form>
</div>

Views/Emprestimo/Excluir.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Excluir Empréstimo";
}

<div class="container bg-dark p-5 rounded-3">

    <div class="mb-5 text-center">
        <h1 class="text-light">Excluir empréstimos</h1>
    </div>

    <form method="post" asp-asp-controller="Emprestimo" asp-action="Excluir">

        <input type="hidden" asp-for=Id />

        <h2 class="text-light">Tem certeza que deseja excluir?</h2>

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro:</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual livro está sendo emprestado?" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controler="Emprestimo" asp-action="">Voltar</a>
        </div>


    </form>
</div>

Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimosModel>

<div class="container">

    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Empréstimos</h1>
        <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar">Cadastrar novo empréstimo</a>
    </div>

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-dark" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-dark" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <table id="Emprestimos" class="table table-dark table-hover">
      <thead>
        <tr>
          <th scope="col">Recebedor</th>
          <th scope="col">Fornecedor</th>
          <th scope="col">Livro</th>
          <th scope="col">Última atualização</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

          @if(Model != null)
          {
              @foreach(var emprestimo in Model)
                {
                  <tr>
                    <th scope="row">@emprestimo.Recebedor</th>
                    <td>@emprestimo.Recebedor</td>
                    <td>@emprestimo.LivroEmprestado</td>
                    <td>@emprestimo.dataUltimaAtualizacao</td>
                    <td>
                        <a asp-controler="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2">Editar</a>
                        <a asp-controler="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2">Excluir</a>
                    </td>
                  </tr> 
                }
  
          }

      </tbody>
    </table>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <h1 class="display-4">Empréstimos on-line</h1>
    <p>Leia sempre!!!</p>

    <div>
        <img src="/img/livro-356951111.png"
    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Emprestimos Livro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoLivros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Emprestimos de Livros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-universal-access-circle mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-book-half mx-2"></i>Emprestimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2023 - EmprestimoLivros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>